name: docker-hub-push
on:
  schedule:
    - cron: '08***'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Default Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: onlyoffice/doc-builder-testing:latest
      - name: Build and push develop Docker
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/debian-develop/Dockerfile
          push: true
          tags: onlyoffice/doc-builder-testing:develop-latest
      - name: Build and push next Release Docker
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/debian-next-release/Dockerfile
          push: true
          tags: onlyoffice/doc-builder-testing:next-release
      - name: Build and push current CentOS docker
        uses: docker/build-push-action@v2
        with:
          file: dockerfiles/centos-7/Dockerfile
          push: true
          tags: onlyoffice/doc-builder-testing:latest-centos
